import { db } from "./index";
import { skills } from "./schema/skills";

const seedSkills = [
  {
    id: "caveman",
    name: "Caveman",
    description: "Ultra-compressed communication mode. Massive token savings with caveman speak while keeping full technical accuracy.",
    tags: ["productivity", "communication", "efficiency"],
    riskScore: 5,
    verified: true,
    installCommand: "curl -O https://raw.githubusercontent.com/JuliusBrussee/caveman/main/SKILL.md",
    sourceUrl: "https://github.com/JuliusBrussee/caveman",
  },
  {
    id: "grill-me",
    name: "Grill Me",
    description: "Forces you to fully think through architecture, edge cases, APIs, UX, and constraints before writing code.",
    tags: ["dev", "review", "architecture", "qa"],
    riskScore: 10,
    verified: true,
    installCommand: "curl -O https://raw.githubusercontent.com/mattpocock/skills/main/grill-me/SKILL.md",
    sourceUrl: "https://github.com/mattpocock/skills",
  },
  {
    id: "diagnose",
    name: "Diagnose",
    description: "Structured debugging workflow: reproduce → isolate → instrument → fix. Methodical approach to bug squashing.",
    tags: ["debugging", "dev", "workflow"],
    riskScore: 8,
    verified: true,
    installCommand: "curl -O https://raw.githubusercontent.com/mattpocock/skills/main/diagnose/SKILL.md",
    sourceUrl: "https://github.com/mattpocock/skills",
  },
  {
    id: "tdd",
    name: "TDD",
    description: "Makes the agent follow proper red-green-refactor loops. Test-driven development discipline for reliable code.",
    tags: ["testing", "dev", "methodology"],
    riskScore: 5,
    verified: true,
    installCommand: "curl -O https://raw.githubusercontent.com/mattpocock/skills/main/tdd/SKILL.md",
    sourceUrl: "https://github.com/mattpocock/skills",
  },
  {
    id: "improve-codebase-architecture",
    name: "Improve Codebase Architecture",
    description: "One of the strongest skills for cleaning AI-generated spaghetti code. Refactors and restructures messy codebases.",
    tags: ["architecture", "dev", "refactoring"],
    riskScore: 20,
    verified: true,
    installCommand: "curl -O https://raw.githubusercontent.com/mattpocock/skills/main/improve-codebase-architecture/SKILL.md",
    sourceUrl: "https://github.com/mattpocock/skills",
  },
  {
    id: "zoom-out",
    name: "Zoom Out",
    description: "Makes the model explain systems from a high-level perspective. Great for understanding architecture before diving into code.",
    tags: ["architecture", "design", "system-design"],
    riskScore: 5,
    verified: true,
    installCommand: "curl -O https://raw.githubusercontent.com/mattpocock/skills/main/zoom-out/SKILL.md",
    sourceUrl: "https://github.com/mattpocock/skills",
  },
  {
    id: "grill-with-docs",
    name: "Grill With Docs",
    description: "Challenges designs against existing docs, ADRs and architecture decisions. Keeps implementations aligned with documented constraints.",
    tags: ["review", "docs", "architecture"],
    riskScore: 10,
    verified: true,
    installCommand: "curl -O https://raw.githubusercontent.com/mattpocock/skills/main/grill-with-docs/SKILL.md",
    sourceUrl: "https://github.com/mattpocock/skills",
  },
  {
    id: "prototype",
    name: "Prototype",
    description: "Builds fast throwaway implementations to validate ideas before committing to a full solution.",
    tags: ["dev", "prototyping", "productivity"],
    riskScore: 15,
    verified: true,
    installCommand: "curl -O https://raw.githubusercontent.com/mattpocock/skills/main/prototype/SKILL.md",
    sourceUrl: "https://github.com/mattpocock/skills",
  },
  {
    id: "handoff",
    name: "Handoff",
    description: "Creates compact context handoff documents between agents. Smooth transitions and knowledge sharing across sessions.",
    tags: ["productivity", "collaboration", "workflow"],
    riskScore: 8,
    verified: true,
    installCommand: "curl -O https://raw.githubusercontent.com/mattpocock/skills/main/handoff/SKILL.md",
    sourceUrl: "https://github.com/mattpocock/skills",
  },
  {
    id: "write-a-skill",
    name: "Write A Skill",
    description: "Creates new Claude Code/OpenCode agent skills. Generate skill definitions with proper structure and metadata.",
    tags: ["dev", "productivity", "tooling"],
    riskScore: 25,
    verified: true,
    installCommand: "curl -O https://raw.githubusercontent.com/mattpocock/skills/main/write-a-skill/SKILL.md",
    sourceUrl: "https://github.com/mattpocock/skills",
  },
  {
    id: "to-prd",
    name: "To PRD",
    description: "Turns conversations into Product Requirement Documents. Structured PRD generation from brainstorming and discussions.",
    tags: ["product", "docs", "planning"],
    riskScore: 5,
    verified: true,
    installCommand: "curl -O https://raw.githubusercontent.com/mattpocock/skills/main/to-prd/SKILL.md",
    sourceUrl: "https://github.com/mattpocock/skills",
  },
  {
    id: "to-issues",
    name: "To Issues",
    description: "Converts PRDs, plans, and requirements into GitHub issues with proper labels, milestones, and assignees.",
    tags: ["project-management", "dev", "github"],
    riskScore: 10,
    verified: true,
    installCommand: "curl -O https://raw.githubusercontent.com/mattpocock/skills/main/to-issues/SKILL.md",
    sourceUrl: "https://github.com/mattpocock/skills",
  },
  {
    id: "triage",
    name: "Triage",
    description: "Issue triaging workflow. Categorizes, prioritizes, and routes incoming issues to the right teams.",
    tags: ["workflow", "github", "productivity"],
    riskScore: 5,
    verified: true,
    installCommand: "curl -O https://raw.githubusercontent.com/mattpocock/skills/main/triage/SKILL.md",
    sourceUrl: "https://github.com/mattpocock/skills",
  },
  {
    id: "git-guardrails",
    name: "Git Guardrails",
    description: "Prevents dangerous git actions like reset --hard, accidental pushes, and other destructive operations.",
    tags: ["git", "devops", "safety"],
    riskScore: 30,
    verified: true,
    installCommand: "curl -O https://raw.githubusercontent.com/mattpocock/skills/main/git-guardrails-claude-code/SKILL.md",
    sourceUrl: "https://github.com/mattpocock/skills",
  },
  {
    id: "setup-pre-commit",
    name: "Setup Pre Commit",
    description: "Adds Husky, lint-staged, tests, and formatting checks to any project. One-command git quality setup.",
    tags: ["git", "devops", "quality"],
    riskScore: 20,
    verified: true,
    installCommand: "curl -O https://raw.githubusercontent.com/mattpocock/skills/main/setup-pre-commit/SKILL.md",
    sourceUrl: "https://github.com/mattpocock/skills",
  },
];

async function main() {
  await db.delete(skills);
  await db.insert(skills).values(seedSkills);
  console.log(`✓ Seeded ${seedSkills.length} skills`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
